@baseUrl=http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Paulo Henrique",
  "email": "paulo2@email.com",
  "password":"123456"
}

### 

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "paulo@email.com",
  "password": "123456"
}

### 

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Minha segunda pergunta",
  "content": "Minha segunda resposta"
}

###

# @name create_answer
POST {{baseUrl}}/questions/ecf1a611-8978-4957-bfab-0e16595ce648/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Minha primeira resposta"
}

###

# @name edit_answer
PUT {{baseUrl}}/answers/e8c24e28-be1d-4eae-9b47-bc7d57ea2606
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Minha primeira resposta editada"
}

### 

# @name fetch_recent_questions
GET {{baseUrl}}/questions
Authorization: Bearer {{authToken}}